NOME: OSVALDO RIBEIRO PEREIRA FILHO
CURSO: ANÁLISE DE DESENVOLVIMENTO DE SISTEMAS
RGM: 38583755
TURNO: NOTURNO

# 1 Apresente em tela (output) toda a base de dados. Pontuação: 0,5 ponto

In [1]:
# Apresentando meu DataFrame sobre animes!

import pandas as pd

nomes_animes=["My Hero Academy", "One Piece", "Naruto", "Bleach", "Vinland Saga", "Dragon Ball"]
autores=["Kohei Horikoshi", "Eiichiro Oda", "Masashi Kishimoto", "Tite Kubo", "Makoto Yukimura", "Akira Toriyama"]
protagonista=["Midoria Izuku", "Monkey D. Luffy", "Naruto Uzumaki", "Ichigo", "Torfinn Karself", "Goku"]
viloes=["All For One", "Marinha", "Ootsutsuki", "Yhwach", "Askeladd", "Deuses da Guerra"]
musicas=["Peace Sing", "The Peak", "Blue Bird", "All Song Are Here", "Troll", "Sorriso Resplandescente"]
ano_de_lancamento=[2016, 1997, 1999, 2004, 2005, 1986]

dados_animes={
    "Nomes de Animes": nomes_animes,
    "Autores": autores,
    "Protagonistas": protagonista,
    "Vilões": viloes,
    "Musicas": musicas,
    "Ano de Lançamento": ano_de_lancamento
}

dados_animes=pd.DataFrame(dados_animes)

display(dados_animes)

,Nomes de Animes,Autores,Protagonistas,Vilões,Musicas,Ano de Lançamento
0,My Hero Academy,Kohei Horikoshi,Midoria Izuku,All For One,Peace Sing,2016
1,One Piece,Eiichiro Oda,Monkey D. Luffy,Marinha,The Peak,1997
2,Naruto,Masashi Kishimoto,Naruto Uzumaki,Ootsutsuki,Blue Bird,1999
3,Bleach,Tite Kubo,Ichigo,Yhwach,All Song Are Here,2004
4,Vinland Saga,Makoto Yukimura,Torfinn Karself,Askeladd,Troll,2005
5,Dragon Ball,Akira Toriyama,Goku,Deuses da Guerra,Sorriso Resplandescente,1986

# 2 Apresente o tamanho do seu dataframe (quantas colunas x linhas). Pontuação: 0,5 pontos

In [ ]:
# Sabendo o tamanho do meu DataFrame!

# shape : retorna a dimensão do DataFrame (número de linhas e colunas).

display("O tamanho de linhas e colunas é:")
display(dados_animes.shape)

'O tamanho de linhas e colunas é:'

(6, 6)

# 3 Acesse a linha (x) e apresente em tela todas as características do item. Pontuação: 0,5 pontos

In [ ]:
# Verificando a linha acessada!

#sample()é usado para gerar uma linha ou coluna aleatória de amostra do quadro de dados do chamador da função.

display("A linha apresentada foi a:")
dados_animes.sample(1)

'A linha apresentada foi a:'

,0,2,3,4,5,6
Nomes de Animes,My Hero Academy,Naruto,Bleach,Vinland Saga,Dragon Ball,Solo Leving

# 4 Verifique se o dataframe está vazio. Pontuação: 0,5 pontos

In [ ]:
# Verificando se meu DataFrame está vazio!

# empty: retorna se o DataFrame está vazio (True) ou não (False).

display("Data frame está vazio?")
dados_animes.empty

'Data frame está vazio?'

False

# 5 Apresente em tela os 5 primeiros registros da base de dados. Pontuação: 0,5 pontos

In [ ]:
# Mostrando os 5 primeiros registros da minha base de dados.

# head (n) retorna as primeiras n linhas de um conjuto de dados. Como padrão, df. head() retorna as 5 primeiras linhas do Data

display("Os 5 primeiros números apresentados são:")
dados_animes.head(5)

'Os 5 primeiros números apresentados são:'

,Nomes de Animes,Autores,Protagonistas,Vilões,Musicas,Ano de Lançamento
0,My Hero Academy,Kohei Horikoshi,Midoria Izuku,All For One,Peace Sing,2016
1,One Piece,Eiichiro Oda,Monkey D. Luffy,Marinha,The Peak,1997
2,Naruto,Masashi Kishimoto,Naruto Uzumaki,Ootsutsuki,Blue Bird,1999
3,Bleach,Tite Kubo,Ichigo,Yhwach,All Song Are Here,2004
4,Vinland Saga,Makoto Yukimura,Torfinn Karself,Askeladd,Troll,2005

# 6 Exclua um item (linha) de sua base de dados. Pontuação: 0,5 pontos

In [ ]:
# Excluindo uma linha do meu DataFrame.

# drop() permite remover linhas ou colunas de um DataFrame com base em rótulos ou índices.
# Para excluir uma coluna, basta especificar o rótulo da coluna e o parâmetro axis=1.
# O parâmetro axis indica o que deve ser removido, sendo 0 para linhas e 1 para colunas.

dados_animes.drop(index = [1], inplace = True)
display(dados_animes)0,

,Nomes de Animes,Autores,Protagonistas,Vilões,Musicas,Ano de Lançamento
0,My Hero Academy,Kohei Horikoshi,Midoria Izuku,All For One,Peace Sing,2016
2,Naruto,Masashi Kishimoto,Naruto Uzumaki,Ootsutsuki,Blue Bird,1999
3,Bleach,Tite Kubo,Ichigo,Yhwach,All Song Are Here,2004
4,Vinland Saga,Makoto Yukimura,Torfinn Karself,Askeladd,Troll,2005
5,Dragon Ball,Akira Toriyama,Goku,Deuses da Guerra,Sorriso Resplandescente,1986

# 7 Adicione um item (linha) na sua base de dados. Pontuação: 0,5 pontos

In [ ]:
# Adicionando uma linha na minha base de dados.

#loc é utilizada para selecionar e filtrar dados em um DataFrame com base em rótulos de
# linhas e colunas, oferecendo uma maneira eficaz de acessar informações específicas de um conjunto de dados.

dados_animes.loc[6] = ["Solo Leving", "Chu-Gong", "Sung-Jinwoo", "Monarcas", "LEveL", "2024"]
display(dados_animes)

,Nomes de Animes,Autores,Protagonistas,Vilões,Musicas,Ano de Lançamento
0,My Hero Academy,Kohei Horikoshi,Midoria Izuku,All For One,Peace Sing,2016
2,Naruto,Masashi Kishimoto,Naruto Uzumaki,Ootsutsuki,Blue Bird,1999
3,Bleach,Tite Kubo,Ichigo,Yhwach,All Song Are Here,2004
4,Vinland Saga,Makoto Yukimura,Torfinn Karself,Askeladd,Troll,2005
5,Dragon Ball,Akira Toriyama,Goku,Deuses da Guerra,Sorriso Resplandescente,1986
6,Solo Leving,Chu-Gong,Sung-Jinwoo,Monarcas,LEveL,2024


# 8 Transponha a coluna para a linha em sua base de dados. Pontuação: 0,5 pontos

In [ ]:
# Transpondo a coluna para a base de dados.

# transpose()função Pandas transpõe o índice e as colunas do dataframe.
# Ele reflete o DataFrame sobre sua diagonal principal, gravando linhas como colunas e vice-versa.

dados_animes = dados_animes.transpose()

display(dados_animes)

,0,2,3,4,5,6
Nomes de Animes,My Hero Academy,Naruto,Bleach,Vinland Saga,Dragon Ball,Solo Leving
Autores,Kohei Horikoshi,Masashi Kishimoto,Tite Kubo,Makoto Yukimura,Akira Toriyama,Chu-Gong
Protagonistas,Midoria Izuku,Naruto Uzumaki,Ichigo,Torfinn Karself,Goku,Sung-Jinwoo
Vilões,All For One,Ootsutsuki,Yhwach,Askeladd,Deuses da Guerra,Monarcas
Musicas,Peace Sing,Blue Bird,All Song Are Here,Troll,Sorriso Resplandescente,LEveL
Ano de Lançamento,2016,1999,2004,2005,1986,2024

# 9 Apresente em tela somente a 1ª e a 2ª coluna (rótulo) da base de dados. Pontuação: 0,5 pontos

In [ ]:
# Apresentando a tela da coluna 1 e 2!

# get()função Pandas é usada para obter um item do objeto para uma determinada
# tecla. A chave pode ser uma ou mais colunas de dataframe. Ele retorna o valor padrão se não for encontrado.

dados_animes.get([0,2])

                                 0                  2
Nomes de Animes    My Hero Academy             Naruto
Autores            Kohei Horikoshi  Masashi Kishimoto
Protagonistas        Midoria Izuku     Naruto Uzumaki
Vilões                 All For One         Ootsutsuki
Musicas                 Peace Sing          Blue Bird
Ano de Lançamento             2016               1999

# 10 Informe como foi desenvolvido o Projeto. Pontuação: 0,5 pontos

In [ ]:
# O projeto foi desenvolvido a partir da idéia de que muitas pessoas tem preconceito com animes,
# visto isso, me interessei e imaginei animes famosos para falar sobre. E com isso, o preceito de citar alguns deles.
# Fiz muitas buscas para achar todas as musicas, autores e anos de lançamento, vilões.

# Os códigos foram desenvolvidos utilizando meu conhecimentos obtidos nas aulas.
# A biblioteca pandas, e o site Data Brics para tirar algumas dúvidas.
# A IA MONICA IM também foi utilizada para saber como eram as estruturas das funções.

# A IDE Google Colab foi usada para o compilamento do código.


print("fonte: https://monica.im/pt_BR")
print("fonte: https://www.databricks.com/glossary/pandas-dataframe")
print("fonte: https://pandas.pydata.org/")
print("fonte: https://www.bing.com/ck/a?!&&p=5b412c640b430f64JmltdHM9MTcxNjMzNjAwMCZpZ3VpZD0xZTA4NTUxOC0yYjY4LTY2ODMtMzZjNS00MTlmMmFiNTY3ZmQmaW5zaWQ9NTIxMw&ptn=3&ver=2&hsh=3&fclid=1e085518-2b68-6683-36c5-419f2ab567fd&psq=protagonista+de+animes&u=a1aHR0cHM6Ly93d3cuYWZpY2lvbmFkb3MuY29tLmJyL3BlcnNvbmFnZW5zLWFuaW1lcy1wb2Rlcm9zb3Mv&ntb=1 ")

fonte: https://www.bing.com/ck/a?!&&p=5b412c640b430f64JmltdHM9MTcxNjMzNjAwMCZpZ3VpZD0xZTA4NTUxOC0yYjY4LTY2ODMtMzZjNS00MTlmMmFiNTY3ZmQmaW5zaWQ9NTIxMw&ptn=3&ver=2&hsh=3&fclid=1e085518-2b68-6683-36c5-419f2ab567fd&psq=protagonista+de+animes&u=a1aHR0cHM6Ly93d3cuYWZpY2lvbmFkb3MuY29tLmJyL3BlcnNvbmFnZW5zLWFuaW1lcy1wb2Rlcm9zb3Mv&ntb=1